module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false,
  theme: {
    extend: {
      animation: {
        "slide-down": "slide-down 0.2s ease-in-out",
      },
      fontFamily: {
        hkr: ["HKGroteskRegular", "sans-serif"],
      },
      spacing: {
        xSpace: "1rem",
      },
      colors: {
        error: {
          main: "#FF4867",
          dark: "#d62744",
          contrast: "#FFF",
        },
        paper: "#FFFFFF",
        default: "#EEEEEE",
        primary: {
          main: "#65ccb8",
          dark: "#57ba98",
          contrast: "#3b945e",
        },
        "modernity-primary-1": "#65ccb8",
        "modernity-primary-2": "#57ba98",
        "modernity-primary-3": "#3b945e",
        "modernity-accent-1": "#f2f2f2",
        "modernity-accent-2": "#182628",

        "effective-primary-1": "#faed26",
        "effective-primary-2": "#9b786f",
        "effective-primary-3": "#9d8d8f",
        "effective-accent-1": "#5a5560",
        "effective-accent-2": "#46344e",

        "vivid-blue-orange-primary-1": "#10e7dc",
        "vivid-blue-orange-primary-2": "#0074e1",
        "vivid-blue-orange-primary-3": "#f79e02",
        "vivid-blue-orange-accent-1": "#1b9ce5",
        "vivid-blue-orange-accent-2": "#6cdaee",

        "unique-primary-1": "#080f5b",
        "unique-primary-2": "#0d19a3",
        "unique-primary-3": "#15db95",
        "unique-accent-1": "#f4e4c1",
        "unique-accent-2": "#e4c580",

        "accent-3": "#d5b3ff",
        "neutral-1": "#ffffff",
        "neutral-2": "#eeeeee",
        "neutral-3": "#a09fa6",
        "neutral-4": "#797979",
        "yellow-1": "#ffcc00",
        "yellow-2": "#ffdb4c",
        "yellow-3": "#ffeb99",
        "blue-1": "#0063f7",
        "blue-2": "#4c92f9",
        "blue-3": "#99c1fc",
        "green-1": "#06c270",
        "green-2": "#51d49b",
        "green-3": "#9be7c6",
        "red-1": "#ec4848",
        "red-2": "#f27f7f",
        "red-3": "#f7b6b6",
        "grey-1": "#eeeeee",
        "grey-2": "#404040",
        "grey-3": "#464646",
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    fontSize: {
      xs: ["0.6875rem", { lineHeight: "1rem" }],
      sm: ["0.9375rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["3rem", { lineHeight: "1" }],
      "6xl": ["3.75rem", { lineHeight: "1" }],
      "7xl": ["4.5rem", { lineHeight: "1" }],
      "8xl": ["6rem", { lineHeight: "1" }],
      "9xl": ["8rem", { lineHeight: "1" }],
    },
  },
  variants: {},
  plugins: [],
};
